### ISSUE TITLE
journal title not appearing in the output file

### ISSUE THREAD

**Issue by gnowgi** [kyledewey/bibtex-markdown#1]
Thanks.  A Cool script for getting something done.  All worked as expected except that the title of the journal did not appear, though it exists in the bib file.

**Comment by kyledewey** [comment]
I'm glad you like the script!  Could you post the .bib file?  I'm not sure why this is happening.

**Comment by gnowgi** [comment]
Thanks. bib file attached
[GN.bib.txt](https://github.com/kyledewey/bibtex-markdown/files/4353125/GN.bib.txt)

**Comment by kyledewey** [comment]
The journal is now output with commit c1885613c64976355d71b1d1c60a5b906acf7421.  It's been awhile since I looked at this (7 years!), and I didn't realize that I manually made the output as opposed to automatically formatting it.
